---
# Version 3.7 for compose files corresponds with
# Docker engine 18.06.0 and newer (per Docker docs).
version: "3"

services:
  db-service:
    build: "./db"
    image: "ntt-image/ms_db_nttmy:1.0"
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: exercisedb
      MYSQL_ROOT_PASSWORD: abc123

  app:
    build: "./app"
    image: "ntt-image/ms_app_nttmy:1.0"
    ports:
      - "5000:5000/tcp"
    links:
      - db-service:db-service
    depends_on:
      - db-service
    restart: on-failure

  pltform:
    build: "./pltform"
    image: "ntt-image/ms_pltform_nttmy:1.0"
    ports:
      - "5001:5001/tcp"
    restart: on-failure

  nginx:
    build: ./nginx
    image: "ntt-image/ms_nginx_nttmy:1.0"
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: on-failure

  frontend:
    restart: always
    build: ./frontend
    image: "ntt-image/ms_frontend_nttmy:1.0"
    ports:
      - '3000:3000'
...
