---
# Version 3.7 for compose files corresponds with
# Docker engine 18.06.0 and newer (per Docker docs).
version: "3"

services:
  db-service:
    build: "./db"
    image: "shahril1987/ms_db_nttmy:2.2"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
  #  env_file:
  #    - test.env
 #   environment:
 #     MYSQL_ROOT_PASSWORD: abc123
 #     MYSQL_DATABASE: exercisedb
 #     MYSQL_USER: shahril
 #     MYSQL_PASSWORD: abc123

  app:
    build: "./app"
    image: "shahril1987/ms_app_nttmy:2.0"
    ports:
      - "5000:5000/tcp"
    links:
      - db-service:db-service
    depends_on:
      - db-service
    restart: on-failure

  pltform:
    build: "./pltform"
    image: "shahril1987/ms_pltform_nttmy:1.0"
    ports:
      - "5001:5001/tcp"
    restart: on-failure

  nginx:
    build: ./nginx
    image: "shahril1987/ms_nginx_nttmy:1.0"
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: on-failure

  frontend:
    restart: always
    build: ./frontend
    image: "shahril1987/ms_frontend_nttmy:1.0"
    ports:
      - '3000:3000'
...
